export const universe = [
    'Nifty 50',
    'Nifty Next 50',
    'Nifty 100',
    'Nifty 200',
    'Nifty 500',
    'Nifty Midcap 150',
    'Nifty Midcap 50',
    'Nifty Full Midcap 100',
    'Nifty Smallcap 250',
    'Nifty Smallcap 50',
    'Nifty MidSmallCap 400',
    'Nifty Auto', 
    'Nifty Bank',
    'Nifty Finance',
    'Nifty FMCG',
    'Nifty IT',
    'Nifty Media',
    'Nifty Metal',
    'Nifty Pharma',
    'Nifty Private Bank',
    'Nifty PSU Bank',
    'Nifty Realty',
    'Nifty Commoditites',
    'Nifty CPSE',
    'Nifty Energy',
    'Nifty Infra',
    'Nifty MNC',
    'Nifty Service'
];